(()=>{
 const SUPABASE_URL='https://jaigrtytkwunnhjyyedn.supabase.co';
 const SUPABASE_KEY='sb_publishable_Y6MGLD8vjitjT8b-CmLA-w_rLpAYj0I';
 const HOUSEHOLD='fonfeder-home',TABLE='shopping_state',DEVICE='familySyncDeviceV1';
 const KEYS=['shopV6','itemsV4','customV2','costcoItemsV1','costcoShopV2','suppersV1','datedMenusV1','myRecipesV1','removedRecipesV1','homeIngredientHiddenV1'];
 let applying=false,ready=false,pushTimer=null,lastRemote='';
 const headers=()=>({'apikey':SUPABASE_KEY,'Authorization':`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json','Prefer':'return=representation'});
 const device=()=>{let d=localStorage.getItem(DEVICE);if(!d){d=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`);localStorage.setItem(DEVICE,d)}return d};
 const snapshot=()=>{const data={};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)data[k]=v});return{version:1,updated_at:new Date().toISOString(),device:device(),data}};
 function apply(s){if(!s?.data)return;applying=true;Object.entries(s.data).forEach(([k,v])=>{if(KEYS.includes(k)&&typeof v==='string')localStorage.setItem(k,v)});applying=false;lastRemote=JSON.stringify(s.data);document.dispatchEvent(new CustomEvent('family-sync-applied',{detail:{updated_at:s.updated_at}}));setTimeout(()=>location.reload(),80)}
 async function getRemote(){const r=await fetch(`${SUPABASE_URL}/rest/v1/${TABLE}?household_id=eq.${encodeURIComponent(HOUSEHOLD)}&select=household_id,state,updated_at&limit=1`,{headers:headers()});if(!r.ok)throw new Error(`Family sync read failed ${r.status}`);return(await r.json())[0]||null}
 async function upsert(s){const r=await fetch(`${SUPABASE_URL}/rest/v1/${TABLE}?on_conflict=household_id`,{method:'POST',headers:{...headers(),'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({household_id:HOUSEHOLD,state:s,updated_at:s.updated_at})});if(!r.ok)throw new Error(`Family sync write failed ${r.status}`)}
 async function push(){if(applying||!ready)return;const s=snapshot(),json=JSON.stringify(s.data);if(json===lastRemote)return;await upsert(s);lastRemote=json;setStatus('Synced')}
 function schedulePush(){if(applying||!ready)return;clearTimeout(pushTimer);pushTimer=setTimeout(()=>push().catch(fail),500)}
 function setStatus(t,bad=false){let e=document.getElementById('familySyncStatus');if(!e){e=document.createElement('div');e.id='familySyncStatus';e.style.cssText='position:fixed;right:12px;top:12px;z-index:9999;background:#fff;border:1px solid #dfe6e1;border-radius:999px;padding:7px 10px;font:700 11px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-shadow:0 3px 12px #0001';document.body.appendChild(e)}e.textContent=`👨‍👩‍👧‍👦 ${t}`;e.style.color=bad?'#a93434':'#0d7a43'}
 function fail(e){console.error(e);setStatus('Sync issue',true)}
 async function boot(){try{setStatus('Connecting…');const remote=await getRemote(),local=snapshot();if(!remote){await upsert(local);lastRemote=JSON.stringify(local.data);ready=true;setStatus('Family synced');return}const rs=remote.state||{};if(!rs.data){await upsert(local);lastRemote=JSON.stringify(local.data);ready=true;setStatus('Family synced');return}const remoteTime=Date.parse(rs.updated_at||remote.updated_at||0)||0,localMarker=Date.parse(localStorage.getItem('familySyncLastRemoteV1')||0)||0;if(localMarker&&remoteTime>localMarker){localStorage.setItem('familySyncLastRemoteV1',rs.updated_at||remote.updated_at||new Date().toISOString());apply(rs);return}if(!localMarker){const hasLocal=KEYS.some(k=>localStorage.getItem(k));if(hasLocal){await upsert(local);lastRemote=JSON.stringify(local.data);localStorage.setItem('familySyncLastRemoteV1',local.updated_at)}else{localStorage.setItem('familySyncLastRemoteV1',rs.updated_at||remote.updated_at||new Date().toISOString());apply(rs);return}}ready=true;lastRemote=JSON.stringify(snapshot().data);setStatus('Family synced');setInterval(async()=>{try{const r=await getRemote(),s=r?.state;if(!s?.data)return;const json=JSON.stringify(s.data);if(json!==lastRemote&&s.device!==device()){localStorage.setItem('familySyncLastRemoteV1',s.updated_at||r.updated_at||new Date().toISOString());apply(s)}}catch(e){fail(e)}},2500)}catch(e){fail(e)}}
 document.addEventListener('shopping-data-changed',schedulePush);window.addEventListener('storage',e=>{if(KEYS.includes(e.key))schedulePush()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();