(()=>{setTimeout(async()=>{
 const URL='https://jaigrtytkwunnhjyyedn.supabase.co',KEY='sb_publishable_Y6MGLD8vjitjT8b-CmLA-w_rLpAYj0I',HOUSE='fonfeder-home';
 const KEYS=['shopV6','costcoShopV2','shoppingFavoritesV1'];let applying=false,pushTimer=null,lastRemote='',lastWrite=0,polling=false;
 const style=document.createElement('style');style.textContent=`.syncPill{display:inline-flex;align-items:center;gap:6px;font-size:10px;font-weight:850;padding:6px 9px;border-radius:999px;background:#eef5ff;color:#1769e8;margin-left:7px}.syncPill:before{content:'';width:6px;height:6px;border-radius:50%;background:#23b26d}.syncPill.wait:before{background:#e5a72d}.syncPill.err{background:#fff0ed;color:#c54b36}.syncPill.err:before{background:#df5a43}`;document.head.appendChild(style);
 function pill(text,cls=''){let p=document.querySelector('.syncPill');if(!p){p=document.createElement('span');p.className='syncPill';document.querySelector('.top h1')?.insertAdjacentElement('afterend',p)}p.className='syncPill '+cls;p.textContent=text}
 function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}function snapshot(){const d={};KEYS.forEach(k=>d[k]=read(k));return d}function sig(d){return JSON.stringify(d||{})}
 function normalize(d){if(!d||typeof d!=='object')return{};const x={...d};if(x.shopV6==null&&x.shopV2!=null)x.shopV6=x.shopV2;delete x.shopV2;return x}
 function merge(local,remote){local=normalize(local);remote=normalize(remote);const out={};['shopV6','costcoShopV2'].forEach(k=>{out[k]={...(remote[k]||{}),...(local[k]||{})}});const lf=local.shoppingFavoritesV1||{},rf=remote.shoppingFavoritesV1||{};out.shoppingFavoritesV1={supermarket:[...new Set([...(rf.supermarket||[]),...(lf.supermarket||[])])],costco:[...new Set([...(rf.costco||[]),...(lf.costco||[])])]};return out}
 function redraw(){try{if(typeof renderShop==='function')renderShop();if(typeof renderCats==='function')renderCats();if(typeof updateCount==='function')updateCount()}catch{}document.dispatchEvent(new CustomEvent('family-sync-applied'))}
 function apply(d){applying=true;KEYS.forEach(k=>{if(d[k]!==undefined)localStorage.setItem(k,JSON.stringify(d[k]))});applying=false;redraw()}
 const headers={'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json','Prefer':'return=representation'};
 async function getRemote(){const r=await fetch(`${URL}/rest/v1/shopping_state?household_id=eq.${encodeURIComponent(HOUSE)}&select=data,updated_at`,{headers});if(!r.ok)throw new Error('read '+r.status);const row=(await r.json())[0];if(row)row.data=normalize(row.data);return row}
 async function write(data){pill('Syncing…','wait');const r=await fetch(`${URL}/rest/v1/shopping_state?household_id=eq.${encodeURIComponent(HOUSE)}`,{method:'PATCH',headers,body:JSON.stringify({data,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('write '+r.status);const row=(await r.json())[0];lastWrite=Date.now();lastRemote=sig(normalize(row?.data||data));pill('Family Sync');return row}
 async function push(){if(applying)return;const remote=await getRemote();const combined=merge(snapshot(),remote?.data||{});apply(combined);await write(combined)}
 function schedulePush(){if(applying)return;clearTimeout(pushTimer);pushTimer=setTimeout(()=>push().catch(()=>pill('Sync issue','err')),220)}
 try{pill('Connecting…','wait');const remote=await getRemote();const combined=merge(snapshot(),remote?.data||{});apply(combined);lastRemote=sig(remote?.data||{});if(sig(combined)!==lastRemote)await write(combined);pill('Family Sync');
 const original=Storage.prototype.setItem;if(!window.__familySyncStorageWrapped){Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(KEYS.includes(k)&&!applying)schedulePush()};window.__familySyncStorageWrapped=true}
 setInterval(async()=>{if(polling||Date.now()-lastWrite<700)return;polling=true;try{const r=await getRemote(),rs=sig(r?.data);if(rs!==lastRemote){lastRemote=rs;const combined=merge(snapshot(),r.data);if(sig(combined)!==sig(snapshot()))apply(combined);if(sig(combined)!==rs)await write(combined)}pill('Family Sync')}catch{pill('Sync issue','err')}finally{polling=false}},1200);window.__familySync={push,getRemote,household:HOUSE};
 }catch(e){console.error('Family sync:',e);pill('Sync issue','err')}
},500)})();