(()=>{setTimeout(async()=>{
 const URL='https://jaigrtytkwunnhjyyedn.supabase.co',KEY='sb_publishable_Y6MGLD8vjitjT8b-CmLA-w_rLpAYj0I',HOUSE='fonfeder-home';
 const KEYS=['shopV6','costcoShopV2','shoppingFavoritesV1'],DEL='familySyncDeletesV1';let applying=false,timer=null,lastRemote='',busy=false,previous={};
 function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}function snap(){const d={};KEYS.forEach(k=>d[k]=read(k));return d}function norm(d){if(!d||typeof d!=='object')return{};const x={...d};if(x.shopV6==null&&x.shopV2!=null)x.shopV6=x.shopV2;delete x.shopV2;return x}function sig(x){return JSON.stringify(x||{})}
 function dels(){return read(DEL)||{shopV6:{},costcoShopV2:{}}}function saveD(d){localStorage.setItem(DEL,JSON.stringify(d))}function noteDeletes(k,oldV,newV){if(k!=='shopV6'&&k!=='costcoShopV2')return;oldV=oldV||{};newV=newV||{};const d=dels();d[k]||(d[k]={});Object.keys(oldV).forEach(n=>{if(!(n in newV))d[k][n]=Date.now()});Object.keys(newV).forEach(n=>delete d[k][n]);saveD(d)}
 function merge(a,b){a=norm(a);b=norm(b);const d=dels(),o={};['shopV6','costcoShopV2'].forEach(k=>{o[k]={...(b[k]||{}),...(a[k]||{})};Object.keys(d[k]||{}).forEach(n=>delete o[k][n])});const af=a.shoppingFavoritesV1||{},bf=b.shoppingFavoritesV1||{};o.shoppingFavoritesV1={supermarket:[...new Set([...(bf.supermarket||[]),...(af.supermarket||[])])],costco:[...new Set([...(bf.costco||[]),...(af.costco||[])])]};o._deleted=d;return o}
 function absorb(raw){const x=norm(raw),remoteD=x._deleted||{};if(remoteD.shopV6||remoteD.costcoShopV2){const d=dels();['shopV6','costcoShopV2'].forEach(k=>{d[k]={...(d[k]||{}),...(remoteD[k]||{})}});saveD(d)}delete x._deleted;return x}
 function status(t){const p=document.querySelector('.syncPill');if(p)p.textContent=t}function redraw(){try{renderShop();renderCats();updateCount()}catch{}document.dispatchEvent(new CustomEvent('family-sync-applied'))}function apply(d){applying=true;KEYS.forEach(k=>{if(d[k]!==undefined)localStorage.setItem(k,JSON.stringify(d[k]))});applying=false;previous=snap();redraw()}
 const headers={'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json','Prefer':'return=representation'};async function remote(){const r=await fetch(URL+'/rest/v1/shopping_state?household_id=eq.'+encodeURIComponent(HOUSE)+'&select=data,updated_at',{headers,cache:'no-store'});if(!r.ok)throw Error('read');const row=(await r.json())[0];if(row)row.data=absorb(row.data);return row}async function write(data){data={...data,_deleted:dels()};status('Syncing…');const r=await fetch(URL+'/rest/v1/shopping_state?household_id=eq.'+encodeURIComponent(HOUSE),{method:'PATCH',headers,body:JSON.stringify({data,updated_at:new Date().toISOString()})});if(!r.ok)throw Error('write');lastRemote=sig(data);status('Family Sync')}
 async function sync(){if(applying||busy)return;busy=true;try{const r=await remote(),combined=merge(snap(),r?.data||{});const clean={...combined};delete clean._deleted;if(sig(clean)!==sig(snap()))apply(clean);await write(clean)}catch{status('Sync issue')}finally{busy=false}}function queue(){clearTimeout(timer);timer=setTimeout(sync,100)}
 try{previous=snap();await sync();const original=Storage.prototype.setItem;if(!window.__familySyncStorageWrapped){Storage.prototype.setItem=function(k,v){let old=null,next=null;if(KEYS.includes(k)&&!applying){try{old=JSON.parse(this.getItem(k)||'null');next=JSON.parse(v)}catch{}}original.call(this,k,v);if(KEYS.includes(k)&&!applying){noteDeletes(k,old,next);previous=snap();queue()}};window.__familySyncStorageWrapped=true}setInterval(async()=>{if(busy)return;try{const r=await remote(),combined=merge(snap(),r?.data||{}),clean={...combined};delete clean._deleted;if(sig(clean)!==sig(snap()))apply(clean)}catch{}},500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});window.addEventListener('focus',sync);window.__familySync={push:sync,getRemote:remote,household:HOUSE};
 }catch{status('Sync issue')}
},350)})();