(()=>{
 let booted=false;
 function boot(attempt=0){
  if(booted)return;const ready=typeof $==='function'&&typeof N==='function'&&typeof renderCats==='function'&&typeof renderShop==='function'&&document.getElementById('items')&&document.getElementById('shopping');if(!ready){if(attempt<80)setTimeout(()=>boot(attempt+1),100);return}booted=true;
  let itemStore=localStorage.getItem('itemStoreV2')||'supermarket',shoppingStore=localStorage.getItem('shoppingStoreV1')||'supermarket',shoppingMode='buy';
  const DEFAULTS=[['Paper Towels','Costco','🧻'],['Water','Costco','💧'],['Detergent','Costco','🧴'],['Soap','Costco','🧼'],['Shampoo','Costco','🧴'],['Water Bottles','Costco','💧'],['Sugar','Costco','🧂'],['Oil','Costco','🫙'],['Avocado Oil','Costco','🥑'],['Towels','Costco','🧺'],['Tissues','Costco','🤧'],['Soda','Costco','🥤'],['Pastrami','Costco','🥩'],['Potato Knishes','Costco','🥔'],['Avocado','Costco','🥑'],['Toothbrush','Costco','🪥'],['Toothpaste','Costco','🦷'],['Wipes','Costco','🧻'],['Pampers','Costco','👶'],['Garbage Bags','Costco','🗑️'],['Hot Cups','Costco','☕'],['Gloves','Costco','🧤'],['Apple Sauce','Costco','🍎'],['Ketchup','Costco','🍅'],['Peanut Butter','Costco','🥜']];
  const readItems=()=>{try{return JSON.parse(localStorage.getItem('costcoItemsV1')||'[]')}catch{return[]}},readShop=()=>{try{return JSON.parse(localStorage.getItem('costcoShopV2')||'{}')}catch{return{}}};
  function ensureDefaults(){const a=readItems();let changed=false;DEFAULTS.forEach(d=>{if(!a.some(x=>N(x[0])===N(d[0]))){a.push(d);changed=true}});if(changed)localStorage.setItem('costcoItemsV1',JSON.stringify(a));return a}ensureDefaults();
  const write=(key,value)=>{localStorage.setItem(key,JSON.stringify(value));document.dispatchEvent(new CustomEvent('shopping-data-changed'))};
  if(!document.getElementById('stableStoreTabsStyle')){const s=document.createElement('style');s.id='stableStoreTabsStyle';s.textContent='.storeTabs{display:grid;grid-template-columns:1fr 1fr;background:#edf1ee;border-radius:14px;padding:4px;gap:4px;margin:10px 0 12px}.storeTabs button{border:0;background:transparent;border-radius:10px;padding:12px 7px;font-weight:900;color:#233129;font-size:14px}.storeTabs button.on{background:#0d7a43;color:#fff;box-shadow:0 1px 5px #0001}.storeHint{font-size:12px;color:#748077;margin:-3px 2px 8px}';document.head.appendChild(s)}
  const tabs=(scope,active)=>`<div class="storeTabs" data-store-scope="${scope}"><button data-store="supermarket" class="${active==='supermarket'?'on':''}">🛒 Supermarket</button><button data-store="costco" class="${active==='costco'?'on':''}">🏬 Costco</button></div>`;
  function ensureTabs(){const ic=$('items')?.querySelector('.card'),sc=$('shopping')?.querySelector('.card');if(ic&&!ic.querySelector('[data-store-scope="items"]')){const h=ic.querySelector('.hdr');if(h){h.insertAdjacentHTML('afterend',tabs('items',itemStore));h.nextElementSibling.insertAdjacentHTML('afterend','<div class="storeHint" id="itemStoreHint"></div>')}}if(sc&&!sc.querySelector('[data-store-scope="shopping"]')){const h=sc.querySelector('.hdr');if(h)h.insertAdjacentHTML('afterend',tabs('shopping',shoppingStore))}}ensureTabs();
  const baseRenderCats=renderCats,baseRenderShop=renderShop,baseToggle=toggleShop,baseDel=delShop,storeQty={};
  function costcoRows(){const costcoItems=ensureDefaults();$('backCats')?.classList.remove('show');if($('itemTitle'))$('itemTitle').textContent='Costco Items';if($('cats'))$('cats').style.display='none';if($('itemRows')){$('itemRows').style.display='block';$('itemRows').innerHTML=costcoItems.map(i=>{const k=N(i[0]),q=storeQty[k]||1;return `<div class="itemrow"><div class="pic">${i[3]?`<img src="${i[3]}">`:i[2]||'🏬'}</div><div class="grow"><b>${esc(i[0])}</b><span class="sub">Costco</span></div><div class="itemAddWrap"><div class="itemQty"><button onclick="__costcoQty('${js(i[0])}',-1)">−</button><span data-cq="${attr(k)}">${q}</span><button onclick="__costcoQty('${js(i[0])}',1)">+</button></div><button class="pill" onclick="__costcoAdd('${js(i[0])}')">Add</button></div></div>`}).join('')}const hint=$('itemStoreHint');if(hint)hint.textContent='Costco has its own separate item list.'}
  window.__costcoQty=(n,d)=>{const k=N(n);storeQty[k]=Math.max(1,(storeQty[k]||1)+d);const e=document.querySelector(`[data-cq="${CSS.escape(k)}"]`);if(e)e.textContent=storeQty[k]};
  window.__costcoAdd=n=>{const costcoItems=ensureDefaults(),k=N(n),i=costcoItems.find(x=>N(x[0])===k);if(!i)return;const m=readShop(),q=storeQty[k]||1,old=m[k];m[k]={name:i[0],cat:'Costco',photo:i[2]||'🏬',customPhoto:i[3]||'',qty:(old?.qty||0)+q,selected:false};storeQty[k]=1;write('costcoShopV2',m);renderShop(shoppingMode);updateCount()};
  renderCats=function(){ensureTabs();if(itemStore==='costco')return costcoRows();baseRenderCats();const hint=$('itemStoreHint');if(hint)hint.textContent='Your supermarket items.'};
  renderShop=function(mode='buy'){ensureTabs();shoppingMode=mode;if($('buyTab'))$('buyTab').classList.toggle('on',mode==='buy');if($('selTab'))$('selTab').classList.toggle('on',mode==='sel');if(shoppingStore==='supermarket')return baseRenderShop(mode);const m=readShop(),a=Object.values(m).filter(x=>!!x.selected===(mode==='sel'));$('shopRows').innerHTML=a.map(x=>`<div class="shoprow"><button class="check ${x.selected?'on':''}" onclick="toggleShop('${js(x.name)}')">${x.selected?'✓':''}</button><div class="pic">${x.customPhoto?`<img src="${x.customPhoto}">`:x.photo}</div><div class="grow"><b>${esc(x.name)}</b><span class="sub">Quantity ${x.qty||1}</span></div><div class="shopQty"><button onclick="__shopQtyChange('${js(x.name)}',-1)">−</button><span>${x.qty||1}</span><button onclick="__shopQtyChange('${js(x.name)}',1)">+</button></div><button class="btn" onclick="delShop('${js(x.name)}')">×</button></div>`).join('')||'<div class="sub" style="padding:18px 4px">Your Costco shopping list is empty.</div>';updateCount()};
  toggleShop=function(n){if(shoppingStore==='supermarket')return baseToggle(n);const m=readShop(),k=N(n);if(m[k]){m[k].selected=!m[k].selected;write('costcoShopV2',m);renderShop(shoppingMode)}};
  delShop=function(n){if(shoppingStore==='supermarket')return baseDel(n);const m=readShop();delete m[N(n)];write('costcoShopV2',m);renderShop(shoppingMode);updateCount()};
  window.__shopQtyChange=function(n,d){if(shoppingStore==='supermarket'){const k=N(n);let m={};try{m=JSON.parse(localStorage.getItem('shopV6')||'{}')}catch{m=shop||{}};const x=m[k];if(!x)return;x.qty=Math.max(1,(Number(x.qty)||1)+d);localStorage.setItem('shopV6',JSON.stringify(m));try{shop=m}catch{}document.dispatchEvent(new CustomEvent('shopping-data-changed'));baseRenderShop(shoppingMode);updateCount();return}const m=readShop(),x=m[N(n)];if(x){x.qty=Math.max(1,(Number(x.qty)||1)+d);write('costcoShopV2',m);renderShop(shoppingMode)}};
  const oldCount=window.updateCount;window.updateCount=function(){try{const a=Object.values(shop||{}).filter(x=>!x.selected).length,b=Object.values(readShop()).filter(x=>!x.selected).length;if($('count'))$('count').textContent=`${a+b} items`}catch{oldCount?.()}};
  function remoteRefresh(e){if(e?.detail?.channel&&e.detail.channel!=='costco')return;if(itemStore==='costco')costcoRows();if(shoppingStore==='costco')renderShop(shoppingMode);updateCount()}
  document.addEventListener('family-costco-reload',remoteRefresh);document.addEventListener('family-sync-applied',remoteRefresh);
  function bindTabs(){ensureTabs();document.querySelectorAll('[data-store-scope="items"] button').forEach(b=>b.onclick=()=>{itemStore=b.dataset.store;localStorage.setItem('itemStoreV2',itemStore);document.querySelectorAll('[data-store-scope="items"] button').forEach(x=>x.classList.toggle('on',x.dataset.store===itemStore));if($('search'))$('search').value='';try{selectedCat=null}catch{}renderCats()});document.querySelectorAll('[data-store-scope="shopping"] button').forEach(b=>b.onclick=()=>{shoppingStore=b.dataset.store;localStorage.setItem('shoppingStoreV1',shoppingStore);document.querySelectorAll('[data-store-scope="shopping"] button').forEach(x=>x.classList.toggle('on',x.dataset.store===shoppingStore));renderShop(shoppingMode)})}bindTabs();setInterval(()=>{ensureTabs();bindTabs()},1500);
  if($('buyTab'))$('buyTab').onclick=()=>renderShop('buy');if($('selTab'))$('selTab').onclick=()=>renderShop('sel');
  const add=$('addItemBtn'),saveBtn=$('saveItem');if(add)add.onclick=()=>{openItemModal();if(itemStore==='costco'&&$('newCat'))$('newCat').innerHTML='<option>Costco</option>'};if(saveBtn)saveBtn.onclick=()=>{const n=$('newName').value.trim();if(!n)return;if(itemStore==='costco'){const a=ensureDefaults();let i=a.find(x=>N(x[0])===N(n));if(!i){i=[n,'Costco','🏬',photoData];a.push(i)}else if(photoData)i[3]=photoData;write('costcoItemsV1',a);closeModal('itemModal');renderCats();return}let i=items.find(x=>N(x[0])===N(n)),c=$('newCat').value;if(!i){i=[n,c,'🛒',photoData];items.push(i);custom.push(i);save('customV2',custom)}else if(photoData)i[3]=photoData;addShop(n,q);closeModal('itemModal');nav('items');selectedCat=c;renderCats()};
  renderCats();renderShop('buy');updateCount();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot());else boot();
})();